### PR TITLE
fix: VueJS infinite query parameters reactivity when `hasInfiniteQueryParam`

### PR DESCRIPTION
**Pull request by Skanislav**
## Status

**READY**

UPD:

Samples updated here: https://github.com/soartec-lab/orval/blob/eecc2622a211d52f27804294a228cf1cd4eda659/samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts

## Description

Fix https://github.com/anymaniax/orval/issues/1378 for detailed issue description

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

-

### CODE REVIEW

**Comment by melloware** [comment]
Assigned @Maxim-Mazurok he is the Vue expert.

**Comment by Skanislav** [comment]
Thanks, after confirmation of fix I can try to add a test for that

**Comment by Skanislav** [comment]
Hey @Maxim-Mazurok, is there anything I can do to speed things up on this one? I checked the existing tests and didn't find any for the useInfiniteQuery implementation. That's probably because this bug wasn't spotted for a long time

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
LGTM I will merge. If @Maxim-Mazurok had and issue we can always fix again.

**Comment by Maxim-Mazurok** [comment]
Hey guys, don't have much time for OSS lately, so probably do not assign me to reviews for now... We do update orval periodically, and I check if generated files changed, and we have pretty good test coverage, so if there will be any bugs - I'll report back to the repo.

As for infinite query, very likely that we missed it, as we don't use infinite query feature. So this probably makes sense. I would suggest creating a functional test in the future, I remember adding a few for the vue query sample. Hope this helps, cheers!

**Pull request merged**
