### PR TITLE
feat(query): Add default mutation key

### PR DESCRIPTION
**Pull request by b-nijhuis-innovadis**
## Status

**READY**

## Description

Add a default mutation key for React Query mutation generation if none was provided.

Fix https://github.com/orval-labs/orval/issues/1249

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Generate a React Query mutation without supplied mutation key to check if default key is used. Generate with a supplied mutation key to check if that one is used instead.

### CODE REVIEW

**Review by melloware — CHANGES_REQUESTED** [review]
looks like unit tests are failing

**Comment by b-nijhuis-innovadis** [comment]
@melloware I tried fixing the tests. But they are still failing. I can't seem to get the tests running locally. I have never used Turbo, do you know what I'm missing? I did do a yarn install.

orval:dev: Error: Cannot find module 'C:\Users\XXX\RiderProjects\orval\node_modules\@orval\core\dist\index.js'. Please verify that the package.json has a valid "main" entry
orval:dev:     at tryPackage (node:internal/modules/cjs/loader:487:19)
orval:dev:     at Module._findPath (node:internal/modules/cjs/loader:771:18)
orval:dev:     at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
orval:dev:     at Module._load (node:internal/modules/cjs/loader:1051:27)
orval:dev:     at Module.require (node:internal/modules/cjs/loader:1311:19)
orval:dev:     at require (node:internal/modules/helpers:179:18)
orval:dev:     at Object.<anonymous> (C:\Users\XX\RiderProjects\orval\packages\orval\dist\bin\orval.js:538:21)
orval:dev:     at Module._compile (node:internal/modules/cjs/loader:1469:14)
orval:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
orval:dev:     at Module.load (node:internal/modules/cjs/loader:1288:32) {
orval:dev:   code: 'MODULE_NOT_FOUND',
orval:dev:   path: 'C:\\Users\\XXX\\RiderProjects\\orval\\node_modules\\@orval\\core\\package.json',
orval:dev:   requestPath: '@orval/core'
orval:dev: }
orval:dev:
orval:dev: Node.js v20.17.0

**Comment by melloware** [comment]
cc @soartec-lab ?

**Review by melloware — DISMISSED** [review]

**Review by melloware — APPROVED** [review]

**Review by soartec-lab — APPROVED** [review]
Thanks!

**Comment by brockklein** [comment]
Thanks for adding this guys! Excited to make use of it.

**Pull request merged**
