### PR TITLE
Fix/post abort signal param

### LINKED ISSUE #1434: Orval does not generate abort signal as third parameter in post request.
## What are the steps to reproduce this issue?

 
```js
generateOrval({

  input: {

    target: "http://localhost:56632/swagger/v1/swagger.json",

    override: {

      transformer: (inputSchema) => {

        return {

          ...inputSchema,

 

          components: {

            ...inputSchema.components,

            schemas: Object.entries(inputSchema.components?.schemas ?? {}).reduce(

              (acc, [schemaName, schema]) => ({

                ...acc,

                [schemaName]: {

                  ...schema,

                  required:

                    "properties" in schema && !isNil(schema.properties)

                      ? Object.keys(

                          reject(

                            (property) => "nullable" in property && !!property.nullable,

                            schema.properties

                          )

                        )

                      : schema

                }

              }),

              {}

            )

          }

        }

      }

    }

  },
  output: {

    target: path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../src/openapi/web-ui"),

    mode: "tags",

    client: "react-query",

    clean: true,

    urlEncodeParameters: true,

    prettier: true,

 

    override: {

      operations: {

        PostPartyLimits: {

          query: {

            useQuery: true,

            useMutation: false,

            signal: true

          }

        }

      },

      useNativeEnums: true,

      useTypeOverInterfaces: true,

      useBigInt: true,

 

      mutator: {

        path: "./src/http/custom-axios-instance.ts",

        name: "customInstance"

      }

    }

  }

})
```
 

## What happens?

postPartyLimits does not have third parameter - signal?: AbortSignal.

 
```js
export const postPartyLimits = (

    partyLimitsRequest: PartyLimitsRequest,

options?: SecondParameter<typeof customInstance>,) => {

     

      

      return customInstance<PartyLimitDto[]>(

      {url: `/PartyLimits`, method: 'POST',

      headers: {'Content-Type': 'application/json', },

      data: partyLimitsRequest

    },

      options);

    }

 

 

export const getPostPartyLimitsQueryKey = (partyLimitsRequest: PartyLimitsRequest,) => {

    return [`/PartyLimits`, partyLimitsRequest] as const;

    }

 

   

export const getPostPartyLimitsQueryOptions = <TData = Awaited<ReturnType<typeof postPartyLimits>>, TError = unknown>(partyLimitsRequest: PartyLimitsRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postPartyLimits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

) => {

 

const {query: queryOptions, request: requestOptions} = options ?? {};

 

  const queryKey =  queryOptions?.queryKey ?? getPostPartyLimitsQueryKey(partyLimitsRequest);

 

 

 

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postPartyLimits>>> = ({ signal }) => postPartyLimits(partyLimitsRequest, requestOptions, signal);

 

     

 

     

 

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postPartyLimits>>, TError, TData> & { queryKey: QueryKey }

}
```
 

## What were you expecting to happen?

 
```js
export const postPartyLimits = (

    partyLimitsRequest: PartyLimitsRequest,

options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {

     

      

      return customInstance<PartyLimitDto[]>(

      {url: `/PartyLimits`, method: 'POST',

      headers: {'Content-Type': 'application/json', },

      data: partyLimitsRequest,signal

    },

      options);

    }
```
 

## Any logs, error output, etc?

 

…

 

## Any other comments?

Looked at the code:

 
```js
!isBodyVerb && hasSignal ? "signal?: AbortSignal\n" : ""

 

const isBodyVerb = import_core2.VERBS_WITH_BODY.includes(verb);

 

import_core2.VERBS_WITH_BODY in this case equals to [ 'post', 'put', 'patch', 'delete' ]

verb = "post"
```
 

Why exists this condition. I use post request as query. Why for post request has no abort signal argument.

 

## What versions are you using?

6.29.1

### LINKED ISSUE #1447: [Regression in 0.30] Using useQuery: true for POST request generates code that does not compile
## What are the steps to reproduce this issue?

1. Have an Orval project with `client: 'react-query'`, and using Orval 0.30.X+
2. Have a POST method that should be output as a query, not as a mutation We need POST because it requires a large request body (path parameters don't work for it).
3. In `orval.config.ts`, set `override.operations.project_aggregation_query.query.useQuery` to `true`.
4. Since orval 0.30, orval outputs code that does not compile. Concretely, the generated `useProjectAggregationQueryQueryOptions` now passes a `signal` parameter to `projectAggregationQuery`, but `projectAggregationQuery` does not actually accept a `signal` parameter.

```typescript
export const projectAggregationQuery = (
  projectId: string,
  aggregationInputInput: AggregationInputInput,
  options?: SecondParameter<typeof instance>,
  // --------------
  // BUG: This function is missing the signal parameter
  // --------------
) => {
  return instance<AggregationResult>(
    {
      url: `/data/analytics/projects/${projectId}/aggregation`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: aggregationInputInput,
    },
    options
  );
};

export const getProjectAggregationQueryQueryKey = (projectId: string, aggregationInputInput: AggregationInputInput) => {
  return [`/data/analytics/projects/${projectId}/aggregation`, aggregationInputInput] as const;
};

export const useProjectAggregationQueryQueryOptions = <
  TData = Awaited<ReturnType<typeof projectAggregationQuery>>,
  TError = ErrorType<HTTPValidationError>,
>(
  projectId: string,
  aggregationInputInput: AggregationInputInput,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof projectAggregationQuery>>, TError, TData>;
    request?: SecondParameter<typeof instance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProjectAggregationQueryQueryKey(projectId, aggregationInputInput);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof projectAggregationQuery>>> = ({ signal }) =>
    // --------------
    // BUG: Here we get the compilation failure. It complains that projectAggregationQuery only support 2-3 parameters, not 4.
    // --------------
    projectAggregationQuery(projectId, aggregationInputInput, requestOptions, signal);

  const customOptions = useDefaultOpenApiQueryOptions({ ...queryOptions, queryKey, queryFn });

  return customOptions as UseQueryOptions<Awaited<ReturnType<typeof projectAggregationQuery>>, TError, TData> & {
    queryKey: QueryKey;
  };
};
```

## What happens?

The code generated by Orval does not compile. `useProjectAggregationQueryQueryOptions` now passes a `signal` parameter to `projectAggregationQuery`, but `projectAggregationQuery` does not actually accept a `signal` parameter.

## What were you expecting to happen?

The generated `projectAggregationQuery` should have a signal parameter.

## Any logs, error output, etc?

N/A

## Any other comments?

This is a new regression. It did not happen in 0.29.x. In 0.29.x, neither `projectAggregationQuery` also did not have a signal parameter, but also `useProjectAggregationQueryQueryOptions` did not pass one.

Here's our orval.config.ts:

```typescript
  analytics: {
    input: {
      target: '../../generated-schemas/analytics.json',
    },
    output: {
      mode: 'split',
      target: 'src/generated',
      client: 'react-query',
      override: {
        mutator: defaultMutator,
        operations: {
          project_aggregation_query: {
            query: {
              // This is a POST request, since it requires a request body, but is actually a query, not a mutation.
              // This forces Orval to generate a query instead of a mutation hook.
              useQuery: true,
            },
          },
        },
      },
    },
  },
```

We found a work-around: We now pass `signal: false` to the override. This restores the behavior in 0.29.x, and lets the code compile successfully. However, it's not ideal. This means that this query cannot be aborted properly by react-query.

## What versions are you using?

**Operating System:** MacOS (but bug is independent from it)
**Package Version:** 0.30.2
**Browser Version:** N/A

### PR DESCRIPTION
**Pull request by wengergruppe**
## Status

Fix #1434
Fix #1447

**READY/WIP/HOLD**

## Description

A few sentences describing the overall goals of the pull request's commits.

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

```bash
> git pull --prune
> git checkout <branch>
> grunt jasmine
```

1.

### CODE REVIEW

**Comment by melloware** [comment]
please run `npm run format`

**Comment by wengergruppe** [comment]
Yes, this PR is for both issues> I assume this is for #1434 and #1447 ???

**Comment by wengergruppe** [comment]
Sorry, perhaps, i didn't run husky hooks. I will check. 
Can you explain me, how to test, that contract is corretly generated and PR will work. With the help of samples directory?   > please run `npm run format`

**Comment by melloware** [comment]
@wengergruppe were you going to fix this so it can be merged?

**Comment by wengergruppe** [comment]
Yes. Today i am going to commit fixes.

**Comment by melloware** [comment]
Ping

**Comment by melloware** [comment]
@wengergruppe where are you at with this?

**Comment by gsaandy** [comment]
@wengergruppe are you fixing the formatting, I can help to fix it if you can provide write access

**Comment by melloware** [comment]
@gsaandy if you want to make a new PR with these changes that would be great.  Then we can close this one and merge yours

**Comment by gsaandy** [comment]
> @gsaandy if you want to make a new PR with these changes that would be great. Then we can close this one and merge yours

@melloware here is the new PR https://github.com/orval-labs/orval/pull/1688.
Note: I only fixed the formatting, the existing tests and build looks good.

**Pull request closed without merging**
